# Generated by Django 4.1.4 on 2022-12-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='staff',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='name',
        ),
    ]
